services:
  blog_service:
    build:
      context: ./WebBlogDjango
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_SERVICE_URL=http://telegram_bot_service:8001
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./WebBlogDjango:/app
    depends_on:
      - telegram_bot_service
      - redis
    networks:
      - blog-ci-cd

  telegram_bot_service:
    build:
      context: ./telegram_bot_service
      dockerfile: Dockerfile
    ports:
      - "8002:8001"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./telegram_bot_service:/app
    networks:
      - blog-ci-cd

  redis:
    image: redis:7.0
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - blog-ci-cd

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "999"
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - blog-ci-cd

networks:
  blog-ci-cd:
    driver: bridge
    enable_ipv6: false

volumes:
  redis_data:
  jenkins_home: